import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { getData } from './api/user'
import Counter from './Counter'

type UserProps = {
  users: {
    id: number,
    name: string
  }[];
}

const Home = ({users}: UserProps) => {
  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main className={styles.main}>

        <div>
        {users.map((user) => (
          <p key={user.id}>
            {user.name}
          </p>
        ))}
        </div>

        <Counter />
      
      </main>
    </>
  )
}
export default Home

export async function getServerSideProps() {
  const data = await getData()
  return {
    props: {
      users: data
    }
  }
}
