//import { useState, useEffect } from 'react'
import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { getData } from './api/user'

type DataProps = {
  users: {
    id: number,
    name: string
  }[];
}

const Home = ({users}: DataProps) => {

  //const [truc, setTruc] = someState<string | undefined>("");

  const count: number = 10;
  const name: string = "Gertrude";

  console.log(name, " ---> name");
  console.log(typeof(name), " ---> typeof name");

  const lightEqualNum = (count: number) => {
    return count;
  }
  lightEqualNum(count);

  const deepEqual = (name: string) => {
    return name;
  } 
  deepEqual(name);

  /*const handleTruc = (e: React.ChangeEvent<HTMLInputElement>) => {
    setTruc(e.target.value);
    console.log(truc, "ok input works");
    e.preventDefault();
  }*/

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>
          {name}
        </div>
        <div>
        {users.map((user) => (
          <p key={user.id}>
            {user.name}
          </p>
        ))}

        </div>
      </main>
    </>
  )
}
export default Home

export async function getServerSideProps() {
  const data = await getData()
  return {
    props: {
      users: data
    }
  }
}

/*
        <div>
          <input id="trucid" name="input" value={truc} onChange={(e) => handleTruc(e)} />
          <p>{truc}</p>
          <button type="button" onClick={() => setTruc("SomeThingElse")}>
            Click
          </button>
        </div>
*/